// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	InsertComment(ctx context.Context, arg InsertCommentParams) error
	InsertPost(ctx context.Context, arg InsertPostParams) error
	QueryGetAllPost(ctx context.Context) ([]Post, error)
	QueryGetCommentById(ctx context.Context, commentPostID sql.NullInt32) ([]Comment, error)
	QueryGetPostById(ctx context.Context, postid int32) (Post, error)
}

var _ Querier = (*Queries)(nil)
